#!/bin/bash

# Manual WiFi testing - one-off commands
# Copy/paste these commands ONE AT A TIME into your terminal
# Commands marked with [NO SUDO] don't need sudo
# Commands marked with [SUDO] require sudo - run them individually

echo "=== MANUAL WiFi HARDENING TEST COMMANDS ==="
echo ""
echo "IMPORTANT: Run these commands ONE AT A TIME in your terminal"
echo "The -60008 error means authorization failed - make sure you use 'sudo' for commands that need it"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "STEP 1: Find your WiFi interface [NO SUDO]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Run this command:"
echo ""
echo "  for iface in en0 en1 en2; do networksetup -getairportnetwork \$iface 2>&1 && echo \"Found: \$iface\" && break; done"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "STEP 2: Get current network (if connected) [NO SUDO]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Replace 'en0' with your interface from Step 1:"
echo ""
echo "  networksetup -getairportnetwork en0"
echo ""
echo "Or for en1:"
echo "  networksetup -getairportnetwork en1"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "STEP 3: List ALL preferred networks [NO SUDO]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Replace 'en0' with your interface:"
echo ""
echo "  networksetup -listpreferredwirelessnetworks en0"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "STEP 4: Test removing ONE network [SUDO - run individually]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Replace 'NETWORK_NAME' with an actual network name from Step 3:"
echo ""
echo "  sudo networksetup -removepreferredwirelessnetwork en0 \"NETWORK_NAME\""
echo ""
echo "Example:"
echo "  sudo networksetup -removepreferredwirelessnetwork en0 \"MyTestNetwork\""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "STEP 5: Verify the network was removed [NO SUDO]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  networksetup -listpreferredwirelessnetworks en0"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "STEP 6: Remove ALL networks except Spectrum-Setup-A1-p* [SUDO]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "ONE-LINER (copy entire line):"
echo ""
echo "  networksetup -listpreferredwirelessnetworks en0 | tail -n +2 | while read net; do net=\$(echo \"\$net\" | xargs); if [[ ! \"\$net\" =~ ^Spectrum-Setup-A1-p ]]; then echo \"Removing: \$net\"; sudo networksetup -removepreferredwirelessnetwork en0 \"\$net\" 2>/dev/null || true; else echo \"Keeping: \$net\"; fi; done"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "STEP 7: Verify only Spectrum networks remain [NO SUDO]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  networksetup -listpreferredwirelessnetworks en0"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "ALTERNATIVE: Test block (copy/paste all at once)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "WIFI_IFACE=\"en0\""
echo "echo \"=== Current Networks ===\""
echo "networksetup -listpreferredwirelessnetworks \"\$WIFI_IFACE\""
echo "echo \"\""
echo "echo \"=== Removing non-Spectrum networks ===\""
echo "networksetup -listpreferredwirelessnetworks \"\$WIFI_IFACE\" | tail -n +2 | while read net; do"
echo "    net=\$(echo \"\$net\" | xargs)"
echo "    if [[ ! \"\$net\" =~ ^Spectrum-Setup-A1-p ]]; then"
echo "        echo \"Removing: \$net\""
echo "        sudo networksetup -removepreferredwirelessnetwork \"\$WIFI_IFACE\" \"\$net\" 2>/dev/null || true"
echo "    else"
echo "        echo \"Keeping: \$net\""
echo "    fi"
echo "done"
echo "echo \"\""
echo "echo \"=== Remaining Networks ===\""
echo "networksetup -listpreferredwirelessnetworks \"\$WIFI_IFACE\""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "TROUBLESHOOTING: If you get -60008 errors"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Make sure you're using 'sudo' for commands that modify networks"
echo "2. Try running 'sudo -v' first to refresh your sudo credentials"
echo "3. Some commands don't need sudo (listing networks, getting current network)"
echo "4. If authorization still fails, you may need to grant Terminal full disk access"
echo "   System Settings > Privacy & Security > Full Disk Access > Add Terminal"
echo ""
